#!/bin/bash
# Usage guide for DeepSeek-R1-Distill-Qwen-14B

echo "================================================================"
echo "DeepSeek-R1-Distill-Qwen-14B - Usage Guide"
echo "================================================================"
echo ""
echo "IMPORTANT: Always activate the virtual environment first!"
echo "  source venv/bin/activate"
echo ""
echo "================================================================"
echo "1. DOWNLOAD MODEL"
echo "================================================================"
echo ""
echo "Option A: 4-bit quantization (RECOMMENDED - ~8GB VRAM)"
echo "  python setup_model.py --4bit"
echo ""
echo "Option B: 8-bit quantization (~14GB VRAM)"
echo "  python setup_model.py --8bit"
echo ""
echo "Option C: Full precision (~30GB VRAM)"
echo "  python setup_model.py"
echo ""
echo "================================================================"
echo "2. INFERENCE / CHAT"
echo "================================================================"
echo ""
echo "Interactive chat:"
echo "  python inference.py --4bit"
echo ""
echo "Single prompt:"
echo "  python inference.py --4bit --prompt 'What is 2+2?'"
echo ""
echo "Math problem example:"
echo "  python inference.py --4bit --prompt 'Solve: 3x + 7 = 22. Please reason step by step and put your answer in \boxed{}.'"
echo ""
echo "================================================================"
echo "3. FINE-TUNING / TRAINING"
echo "================================================================"
echo ""
echo "Basic LoRA fine-tuning (QLoRA with 4-bit):"
echo "  python train_model.py --use-lora --4bit --epochs 3"
echo ""
echo "With custom dataset from HuggingFace:"
echo "  python train_model.py --use-lora --4bit --dataset 'username/dataset-name' --epochs 5"
echo ""
echo "With local JSON dataset:"
echo "  python train_model.py --use-lora --4bit --dataset './my_data.jsonl' --epochs 3"
echo ""
echo "With Weights & Biases logging:"
echo "  python train_model.py --use-lora --4bit --use-wandb"
echo ""
echo "================================================================"
echo "4. ADVANCED USAGE"
echo "================================================================"
echo ""
echo "Using vLLM for fast inference:"
echo "  pip install vllm"
echo "  python -m vllm.entrypoints.openai.api_server \\"
echo "    --model deepseek-ai/DeepSeek-R1-Distill-Qwen-14B \\"
echo "    --tensor-parallel-size 1"
echo ""
echo "Using SGLang:"
echo "  pip install sglang"
echo "  python -m sglang.launch_server \\"
echo "    --model deepseek-ai/DeepSeek-R1-Distill-Qwen-14B \\"
echo "    --trust-remote-code"
echo ""
echo "================================================================"
echo "5. TIPS & BEST PRACTICES"
echo "================================================================"
echo ""
echo "- Use temperature 0.6 (range 0.5-0.7) for best results"
echo "- For math: Ask to put answer in \boxed{}"
echo "- Avoid system prompts, put everything in user prompt"
echo "- Model thinks using <think> tags - this is normal"
echo "- For benchmarking: run multiple times and average"
echo ""
echo "================================================================"
echo "For more details, see README.md"
echo "================================================================"
